### ISSUE TITLE
docs does not show connection string

### ISSUE THREAD

**Issue by nconforti93** [exasol/sqlserver-virtual-schema#11]
The user guide does not handle the connection string properly.

Via connection string definition: 'jdbc:sqlserver://:/';

You need to escape the bracket characters:

Via connection string definition with a backwards slash before each of the bracket characters (\< and \>): 'jdbc:sqlserver://\<server name\>:\<port\>/\<database name\>';

in order for it to display properly

**Comment by kaklakariada** [comment]
Thanks for your report, I fixed it in #12
